wikis2pages-demo:
  src: https://$GITHUB_TOKEN@github.com/codeenigma/wikis2pages-demo.wiki.git
  src_branch: master
  src_subdir: ''
  dest: https://$GITHUB_TOKEN@github.com/codeenigma/wikis2pages-demo.git
  dest_branch: master
  dest_subdir: wiki
  title: Wikis 2 Pages - Demo
  type: basic
  base_url: https://codeenigma.github.io/wikis2pages-demo/wiki